AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Secure Production Evaluation Harness Engine Infrastructure
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - test
    - prod
  ProjectName:
    Type: String
    Default: evaluation
  DashboardApiKeyToken:
    Type: String
    NoEcho: true
    Description: Token used by the dashboard to access the API
    Default: vn2cyz37EzYA4ivBYAYhKVr9YfUZsabh
    MinLength: 20
    MaxLength: 100
  LogRetentionDays:
    Type: Number
    Default: 7
    AllowedValues:
    - 3
    - 7
    - 30
  RunnerSchedule:
    Type: String
    Default: cron(0 2 * * ? *)
    Description: EventBridge schedule for evaluation runs
  JudgeSchedule:
    Type: String
    Default: cron(30 2 * * ? *)
    Description: EventBridge schedule for judging completed runs
Resources:
  NetworkStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.us-west-2.amazonaws.com/aws-sam-cli-managed-default-samclisourcebucket-9mojol21uxjb/5b0576aee35cebdd2cba019e7768dc80.template
      Parameters:
        Environment:
          Ref: Environment
        ProjectName:
          Ref: ProjectName
    Metadata:
      SamResourceId: NetworkStack
  DatabaseStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.us-west-2.amazonaws.com/aws-sam-cli-managed-default-samclisourcebucket-9mojol21uxjb/4c0d638e4d43670d5ecb5420add697e0.template
      Parameters:
        Environment:
          Ref: Environment
        ProjectName:
          Ref: ProjectName
        RdsSecurityGroupId:
          Fn::GetAtt:
          - NetworkStack
          - Outputs.RdsSecurityGroupId
        PrivateSubnetIds:
          Fn::GetAtt:
          - NetworkStack
          - Outputs.PrivateSubnetIds
    Metadata:
      SamResourceId: DatabaseStack
  LambdaRoleStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.us-west-2.amazonaws.com/aws-sam-cli-managed-default-samclisourcebucket-9mojol21uxjb/1f19d416207b6c7b73605c214160772a.template
      Parameters:
        Environment:
          Ref: Environment
        ProjectName:
          Ref: ProjectName
        DatabaseSecretArn:
          Fn::GetAtt:
          - DatabaseStack
          - Outputs.DatabaseSecretArn
    Metadata:
      SamResourceId: LambdaRoleStack
  HydrateStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.us-west-2.amazonaws.com/aws-sam-cli-managed-default-samclisourcebucket-9mojol21uxjb/1329e73182a001e9ec463e0775c6449c.template
      Parameters:
        Environment:
          Ref: Environment
        ProjectName:
          Ref: ProjectName
        LambdaExecutionRole:
          Fn::GetAtt:
          - LambdaRoleStack
          - Outputs.LambdaExecutionRoleArn
        LambdaSecurityGroupId:
          Fn::GetAtt:
          - NetworkStack
          - Outputs.LambdaSecurityGroupId
        PrivateSubnetIds:
          Fn::GetAtt:
          - NetworkStack
          - Outputs.PrivateSubnetIds
        DatabaseEndpoint:
          Fn::GetAtt:
          - DatabaseStack
          - Outputs.DatabaseEndpoint
        DatabasePort:
          Fn::GetAtt:
          - DatabaseStack
          - Outputs.DatabasePort
        DatabaseName:
          Fn::GetAtt:
          - DatabaseStack
          - Outputs.DatabaseName
        DatabaseSecretArn:
          Fn::GetAtt:
          - DatabaseStack
          - Outputs.DatabaseSecretArn
        LogRetentionDays:
          Ref: LogRetentionDays
    Metadata:
      SamResourceId: HydrateStack
  RunnerStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.us-west-2.amazonaws.com/aws-sam-cli-managed-default-samclisourcebucket-9mojol21uxjb/21dd6c4d24e9d5f650bcb7b0b135d14f.template
      Parameters:
        Environment:
          Ref: Environment
        ProjectName:
          Ref: ProjectName
        LambdaExecutionRole:
          Fn::GetAtt:
          - LambdaRoleStack
          - Outputs.LambdaExecutionRoleArn
        LambdaSecurityGroupId:
          Fn::GetAtt:
          - NetworkStack
          - Outputs.LambdaSecurityGroupId
        PrivateSubnetIds:
          Fn::GetAtt:
          - NetworkStack
          - Outputs.PrivateSubnetIds
        DatabaseEndpoint:
          Fn::GetAtt:
          - DatabaseStack
          - Outputs.DatabaseEndpoint
        DatabasePort:
          Fn::GetAtt:
          - DatabaseStack
          - Outputs.DatabasePort
        DatabaseName:
          Fn::GetAtt:
          - DatabaseStack
          - Outputs.DatabaseName
        DatabaseSecretArn:
          Fn::GetAtt:
          - DatabaseStack
          - Outputs.DatabaseSecretArn
        LogRetentionDays:
          Ref: LogRetentionDays
        Schedule:
          Ref: RunnerSchedule
    Metadata:
      SamResourceId: RunnerStack
  JudgeStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.us-west-2.amazonaws.com/aws-sam-cli-managed-default-samclisourcebucket-9mojol21uxjb/f9277387c804260274c46f32761d85f1.template
      Parameters:
        Environment:
          Ref: Environment
        ProjectName:
          Ref: ProjectName
        LambdaExecutionRole:
          Fn::GetAtt:
          - LambdaRoleStack
          - Outputs.LambdaExecutionRoleArn
        LambdaSecurityGroupId:
          Fn::GetAtt:
          - NetworkStack
          - Outputs.LambdaSecurityGroupId
        PrivateSubnetIds:
          Fn::GetAtt:
          - NetworkStack
          - Outputs.PrivateSubnetIds
        DatabaseEndpoint:
          Fn::GetAtt:
          - DatabaseStack
          - Outputs.DatabaseEndpoint
        DatabasePort:
          Fn::GetAtt:
          - DatabaseStack
          - Outputs.DatabasePort
        DatabaseName:
          Fn::GetAtt:
          - DatabaseStack
          - Outputs.DatabaseName
        DatabaseSecretArn:
          Fn::GetAtt:
          - DatabaseStack
          - Outputs.DatabaseSecretArn
        LogRetentionDays:
          Ref: LogRetentionDays
        Schedule:
          Ref: JudgeSchedule
    Metadata:
      SamResourceId: JudgeStack
  ApiStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: https://s3.us-west-2.amazonaws.com/aws-sam-cli-managed-default-samclisourcebucket-9mojol21uxjb/bb7c775973d8284c6e1a91201d5e3bd7.template
      Parameters:
        Environment:
          Ref: Environment
        ProjectName:
          Ref: ProjectName
        LambdaExecutionRole:
          Fn::GetAtt:
          - LambdaRoleStack
          - Outputs.LambdaExecutionRoleArn
        LambdaSecurityGroupId:
          Fn::GetAtt:
          - NetworkStack
          - Outputs.LambdaSecurityGroupId
        PrivateSubnetIds:
          Fn::GetAtt:
          - NetworkStack
          - Outputs.PrivateSubnetIds
        DatabaseEndpoint:
          Fn::GetAtt:
          - DatabaseStack
          - Outputs.DatabaseEndpoint
        DatabasePort:
          Fn::GetAtt:
          - DatabaseStack
          - Outputs.DatabasePort
        DatabaseName:
          Fn::GetAtt:
          - DatabaseStack
          - Outputs.DatabaseName
        DatabaseSecretArn:
          Fn::GetAtt:
          - DatabaseStack
          - Outputs.DatabaseSecretArn
        Token:
          Ref: DashboardApiKeyToken
        LogRetentionDays:
          Ref: LogRetentionDays
    Metadata:
      SamResourceId: ApiStack
Outputs:
  ApiEndpointUrl:
    Description: Secured API Gateway endpoint
    Value:
      Fn::GetAtt:
      - ApiStack
      - Outputs.ApiGatewayUrl
  VpcId:
    Description: Evaluation Harness VPC ID
    Value:
      Fn::GetAtt:
      - NetworkStack
      - Outputs.VpcId
  DatabaseEndpoint:
    Description: Evaluation database endpoint
    Value:
      Fn::GetAtt:
      - DatabaseStack
      - Outputs.DatabaseEndpoint
  HydrateLambdaArn:
    Description: Hydrate Lambda ARN
    Value:
      Fn::GetAtt:
      - HydrateStack
      - Outputs.HydrateLambdaArn
  RunnerLambdaArn:
    Description: Runner Lambda ARN
    Value:
      Fn::GetAtt:
      - RunnerStack
      - Outputs.RunnerLambdaArn
  JudgeLambdaArn:
    Description: Judge Lambda ARN
    Value:
      Fn::GetAtt:
      - JudgeStack
      - Outputs.JudgeLambdaArn
